export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_MARINAS = 'FETCH_MARINAS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ADVERTISEMENT = 'FETCH_ADVERTISEMENT';
export const CLEAR_ADVERTISEMENT = 'CLEAR_ADVERTISEMENT';
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const CLEAR_BUSINESSES = 'CLEAR_BUSINESSES';

export const SUCCESS = 'SUCCESS';
export const REQUEST = 'REQUEST';
export const FAILURE = 'FAILURE';
